version: "3.9"
services:
  user-service:
    build:
      context: .
      dockerfile: src/user-service/Dockerfile
    container_name: user-service
    ports:
      - "3000:3000"
    depends_on:
      - user-service-db
      - kafka
    environment:
      - KAFKA_BROKER_HOST=kafka:9092
  email-service:
    build:
      context: .
      dockerfile: src/email-service/Dockerfile
    container_name: email-service
    ports:
      - "4000:4000"
    depends_on:
      - email-service-db
      - kafka
    environment:
      - KAFKA_BROKER_HOST=kafka:9092
  user-service-db:
    image: mongo:latest
    container_name: mongo-user-service-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data1:/data/db
  email-service-db:
    image: mongo:latest
    container_name: mongo-email-service-db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data2:/data/db
  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "true"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

volumes:
  mongo_data1:
  mongo_data2:
